#!/bin/csh
#SBATCH --clusters=c3
#SBATCH --nodes=16
#SBATCH -t 16:00:00

# source /lustre/f2/dev/Hemant.Khatri/MOM6-examples/build/intel/env

srun -n 512 /lustre/f2/dev/Hemant.Khatri/MOM6-examples/build/intel/ocean_only/repro/MOM6
